apiVersion: v1
kind: Service
metadata:
  name: mongo-client-service
spec:
  type: NodePort
  selector:
    app: mongo-client
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30110